name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      shell: pwsh
      run: |
        $username = $GITHUB_REPOSITORY.Split("/")[0]
        
        cd src/FSX
        dotnet nuget add source --username $username --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/$username/index.json"
        dotnet pack --configuration Release
        dotnet nuget push "bin/Release/FSX.1.0.0.nupkg"  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
